DiplomStore/Components/CartSummaryViewComponent.cs
using DiplomStore.BLL.DTO.Cart;
using Microsoft.AspNetCore.Mvc;

namespace DiplomStore.Components
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private CartDTO Cart;
        public CartSummaryViewComponent(CartDTO cart)
        {
            Cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(Cart);
        }
    }
}

DiplomStore/Controllers/CartController.cs
using DiplomStore.BLL.DTO;
using DiplomStore.BLL.Services.Intefaces;
using DiplomStore.ViewsModels.Cart;
using Microsoft.AspNetCore.Mvc;
using DiplomStore.BLL.DTO.Cart;
using DiplomStore.Domain.Entity;

namespace DiplomStore.Controllers
{
    public class CartController:Controller
    {
        private readonly ITovarService tovars;
        private readonly ITitleService Titles;
        private readonly ICategoryService Category;
        private readonly CartDTO cart;

        public CartController(ITovarService tv, ITitleService tit, ICategoryService cat, CartDTO car)
        {
            tovars = tv;
            Titles = tit;
            Category = cat;
            cart = car;
        }

        public IActionResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public IActionResult AddToCart(int TovarsId, string returnUrl)
        {
            Tovars tovar = tovars.GetTovar().FirstOrDefault(t=>t.TovarsId == TovarsId);
            if(tovar !=null)
            {
                cart.AddItem(tovar, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public IActionResult RemoveFromCart(int TovarsId, string returnUrl)
        {
            Tovars tovar = tovars.Models().FirstOrDefault(t => t.TovarsId == TovarsId);
            if (tovar != null)
            {
                cart.RemoveLine(tovar);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public IActionResult RemoveItemFromCart(int TovarsId, string returnUrl)
        {
            Tovars tovar = tovars.Models().FirstOrDefault(t => t.TovarsId == TovarsId);
            if (tovar != null)
            {                
                cart.RemoveItem(tovar);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

    }
}

DiplomStore/Controllers/OrderController.cs
using AutoMapper;
using DiplomStore.BLL.DTO;
using DiplomStore.BLL.DTO.Cart;
using DiplomStore.BLL.Services.Intefaces;
using DiplomStore.Domain.Entity;
using DiplomStore.ViewsModels.Order;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Text;
using XSystem.Security.Cryptography;

namespace DiplomStore.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService db;
        private readonly UserManager<AppUser> userManager;
        private CartDTO cart;
        public OrderController(IOrderService _db, CartDTO cartDTO, UserManager<AppUser> _userManager)
        {
            db = _db;
            cart = cartDTO;
            userManager = _userManager;
        }
        public ViewResult Checkout() => View(new OrderViewModel());
        /// <summary>
        /// Проверяет форму заполнения данных
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Checkout(OrderViewModel model)
        {
            model.DateTime = DateTime.Now;
            //Если товаров в корзине нету, то выходит ошибка и сообщение
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Корзина пуста");
            }
            if (ModelState.IsValid)
            {
                PaidViewModel paid = new PaidViewModel();
                var user = userManager.Users.FirstOrDefault(p => p.UserName == User.Identity.Name);

                model.User = user;

                var mapCategor = new MapperConfiguration(c => c.CreateMap<OrderViewModel, Order>()).CreateMapper();
                //сопоставление объектов OrderViewModel в Order                                    
                var order = mapCategor.Map<OrderViewModel, Order>(model);
                //Присваиваем переменной товары из корзине
                order.Lines = cart.Lines.ToArray();
                db.SaveOrder(order);
                paid.Order = model;
                paid.Cart = cart;
                return View("Paid",paid);
            }
            return View(model);
        }            

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }
    }
}

DiplomStore/Controllers/TovarController.cs
using AutoMapper;
using DiplomStore.BLL.Services.Intefaces;
using DiplomStore.Domain.Entity;
using DiplomStore.ViewsModels.Category;
using DiplomStore.ViewsModels.Title;
using DiplomStore.ViewsModels.Tovar;
using Microsoft.AspNetCore.Mvc;

namespace DiplomStore.Controllers
{
    public class TovarController:Controller
    {
        private readonly ITovarService Tovars;
        private readonly ICategoryService Categories;
        private readonly ITitleService Titles;
        public TovarController(ITovarService ctx, ICategoryService categories, ITitleService titles)
        {
            Tovars = ctx;
            Categories = categories;
            Titles = titles;
        }
    /// <summary>
    /// Выводит товары связанные с категориями
    /// </summary>
    /// <param name="searhString">Поисковая строка</param>
    /// <param name="CategoriesId"></param>
    /// <param name="selectedTitle">Выбранный тайтл</param>
    /// <param name="page"></param>
    /// <returns></returns>
        [HttpGet]
        public IActionResult TovarAndCategoryList(string searhString, int CategoriesId, int[] selectedTitle, int page = 1)
        {
            TovarAndCategoryListViewModel TovarCategory = new TovarAndCategoryListViewModel();
            
            var map = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов Tovars в TovarViewModel                                    
            var tovars = map.Map<IEnumerable<Tovars>, List<TovarViewModel>>(Tovars.Models());
            //Находим товары связанные с категориями
            TovarCategory.Tovar = tovars.Where(p => p.category.CategoriesId == CategoriesId).ToList();
            //Всего товаров на странице
            int pageSize = 6;
            //Всего товаров
            var count = tovars.Count();
            //Получение товаров
            var item = tovars.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel(item, pageViewModel);
            TovarCategory.IndexViewModel = viewModel;
            
            var cat = Categories.Models().FirstOrDefault(p => p.CategoriesId == CategoriesId);
            var mapCategor = new MapperConfiguration(c => c.CreateMap<Categories, CategoryViewModel>()).CreateMapper();
            //сопоставление объектов Categories в CategoryViewModel                                    
            var categor = mapCategor.Map<Categories, CategoryViewModel>(cat);

            var mapTile = new MapperConfiguration(c => c.CreateMap<Titles, TitleViewModel>()).CreateMapper();
            //сопоставление объектов Titles в TitleViewModel          
            TovarCategory.Titles = mapTile.Map<IEnumerable<Titles>, List<TitleViewModel>>(Titles.Models().Where(p => p.tovars.Any(d => d.isValids) && p.tovars.Any(d => d.CategoryId == CategoriesId)));

            TovarCategory.Category = categor;
            List<TovarViewModel> t = new List<TovarViewModel>();
            if (!string.IsNullOrEmpty(searhString))
            {
                if(selectedTitle != null)
                {
                    foreach (var c in Titles.Models().Where(p => selectedTitle.Contains(p.TitlesId)))
                    {
                        // Добавляем в лист товары, связанных одной категорией или тайтлом
                        t.AddRange(item.Where(p => p.category.CategoriesId == CategoriesId & p.TitleId == c.TitlesId).ToList());

                    }
                    if (t.Count > 0)
                    {
                        //получаем товар по поисковой строке
                        TovarCategory.Tovar = t.Where(p=>p.name.ToLower().Contains(searhString.ToLower())).ToList();
                        TovarCategory.selectTitle.AddRange(selectedTitle);
                        return View("TovarAndCategoryList", TovarCategory);
                    }
                    else
                    {

                        t.AddRange(tovars.Where(p => p.name.ToLower().Contains(searhString.ToLower()) & p.category.CategoriesId == CategoriesId));
                        TovarCategory.Tovar = t;
                    }
                }

                
               
            }
            TovarCategory.Tovar = item;
            return View("TovarAndCategoryList",TovarCategory);
        }
        /// <summary>
        /// Выводит товары связанные с тайтлами
        /// </summary>
        /// <param name="TitleId">Поисковая строка</param>
        /// <param name="searhString"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult TovarAndTitleList(int TitleId , string searhString, int page=1)
        {
            TovarAndTitleViewModel TovarTitle = new TovarAndTitleViewModel();
            var map = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов TovarDTO в TovarListViewModel                                    
            var tovars = map.Map<IEnumerable<Tovars>, List<TovarViewModel>>(Tovars.Models());

            var tit = Titles.Models().FirstOrDefault(p => p.TitlesId == TitleId);
            var mapTile = new MapperConfiguration(c => c.CreateMap<Titles, TitleViewModel>()).CreateMapper();

            if (!string.IsNullOrEmpty(searhString))
            {   
                //Получаем товары по поисковой строке
                TovarTitle.tovars = tovars.Where(p => p.titles.TitlesId == TitleId & p.name.Contains(searhString)).ToList();
                //сопоставление объектов Titles в TitleViewModel                      
                TovarTitle.title = mapTile.Map<Titles, TitleViewModel>(tit);
                return View(TovarTitle);
            }
            int pageSize = 6;
            var count = tovars.Count();
            var item = tovars.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel(item, pageViewModel);
            TovarTitle.IndexViewModel = viewModel;

            TovarTitle.tovars = item.Where(p => p.titles.TitlesId == TitleId).ToList();
            ///сопоставление объектов Titles в TitleViewModel                      
            TovarTitle.title = mapTile.Map<Titles, TitleViewModel>(tit);
            return View(TovarTitle);
        }

        public IActionResult TovarIndex(int TovarId)
        {
            TovarsTitleViewModel TovarTitle = new TovarsTitleViewModel();
            var map = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов Tovars в TovarViewModel                                    
            var tovar = map.Map<Tovars, TovarViewModel>(Tovars.Models().FirstOrDefault(p=>p.TovarsId == TovarId ));
            TovarTitle.Tovar = tovar;
            var c = Titles.Models().FirstOrDefault(t=>t.TitlesId == tovar.TitleId);

            var maptitle = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов Tovars в TovarViewModel                                    
            var tovars = maptitle.Map<IEnumerable<Tovars>, List<TovarViewModel>>(Tovars.Models().Where(t => t.TitleId == tovar.TitleId && t.TovarsId !=TovarId));

            TovarTitle.Tovars = tovars;
            return View(TovarTitle);

        }
        /// <summary>
        /// Выводит товары свзяанные с категорией и выбраннысм тайтлами
        /// </summary>
        /// <param name="selectedTitle"></param>
        /// <param name="CategoriesId"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult IndexTovarOfTitle(int[] selectedTitle,int CategoriesId, int page = 1)
        {
            
            TovarAndCategoryListViewModel TovarCategory = new TovarAndCategoryListViewModel();
            var map = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов TovarDTO в TovarListViewModel                                    
            var tovars = map.Map<IEnumerable<Tovars>, List<TovarViewModel>>(Tovars.Models());

            int pageSize = 6;
            var count = tovars.Count();
            var item = tovars.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel(item, pageViewModel);
            TovarCategory.IndexViewModel = viewModel;

            List<TovarViewModel> t = new List<TovarViewModel>();
            if(selectedTitle != null)
            {
                foreach (var c in Titles.Models().Where(p => selectedTitle.Contains(p.TitlesId)))
                {
                    t.AddRange(item.Where(p => p.category.CategoriesId == CategoriesId & p.TitleId == c.TitlesId).ToList());

                }
                if(t.Count >0)
                {
                    TovarCategory.Tovar = t;
                    TovarCategory.selectTitle.AddRange(selectedTitle);
                }
                else
                {
                    t.AddRange(tovars.Where(p => p.category.CategoriesId == CategoriesId));
                    TovarCategory.Tovar = t;
                }
                
            }
          
            var mapTile = new MapperConfiguration(c => c.CreateMap<Titles, TitleViewModel>()).CreateMapper();
            //сопоставление объектов TovarDTO в TovarListViewModel                                    
            var Title = mapTile.Map<IEnumerable<Titles>, List<TitleViewModel>>(Titles.Models().Where(p => p.tovars.Any(d => d.isValids) && p.tovars.Any(d => d.CategoryId == CategoriesId)));
           

DiplomStore/Controllers/UserController.cs
using AutoMapper;
using DiplomStore.BLL.Services.Intefaces;
using DiplomStore.Domain.Entity;
using DiplomStore.ViewsModels.Order;
using DiplomStore.ViewsModels.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace DiplomStore.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IOrderService db;
        private readonly UserManager<AppUser> userManager;
        public UserController(IOrderService orderService, UserManager<AppUser> _userManager)
        {
            db = orderService;
            userManager = _userManager;
        }
        public ViewResult Index()
        {
            UserViewModel userOrd = new UserViewModel();
            var user = userManager.Users.FirstOrDefault(p => p.UserName == User.Identity.Name);
            var map = new MapperConfiguration(c => c.CreateMap<Order, OrderViewModel>()).CreateMapper();
            //сопоставление объектов Order в OrderViewModel                    
            var order = map.Map<IEnumerable<Order>, List<OrderViewModel>>(db.Orders().Where(p => p.User.Id == user.Id));
            userOrd.orders = order;

            return View(userOrd);
        }
        public IActionResult DeleteOrder(int IdOrder)
        {
            if (IdOrder != 0)
            {
                db.Delete(IdOrder);
                return RedirectToAction("Index");
            }
            return View("Index");
        }
    }
}

DiplomStore/Views/Cart/Index.cshtml
@model CartIndexViewModel
@{Layout="_Layout";}

<div class="navn  sticky-top ">
    <nav class="navbar navbar-expand-lg navbar-light shadow-lg "style="background-color: #1968AA">
      <div class="container ">
        <a asp-action="Index" asp-controller="Home" class="navbar-brand d-none d-lg-flex" >
          <img src="~/img/logo/logo-1.jpg" class="" alt="Logo" />
       
        </a>
        <form class="d-flex w-75 " asp-action="TovarSearch" asp-controller="Tovar"  method="get">          
          <input class="form-control me-2" name="searhString" type="search" placeholder="Поиск" aria-label="Search">          
        </form>
        <div class="container-fluid  w-25">        
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
         
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 w-100">
              <li class="nav-item text-center rounded-1 w-100 bg-light " >
                  @await Component.InvokeAsync("CartSummary")
              </li>
              <li class="rounded-1 bg-light w-100 d-lg-none d-xl-none d-xxl-none nav-item ">
                <a class="nav-link" asp-action="TitleIndex" asp-controller="Home">Список тайтолов</a>
              </li> 
               <li class="rounded-1 bg-light w-100 d-lg-none d-xl-none d-xxl-none nav-item ">
                <a class="nav-link" asp-action="CategoryIndex" asp-controller="Home">Список категорий</a>
              </li>
              <li class="nav-item ms-3">
                <a class="nav-link text-light  d-none d-xxl-block d-xl-block d-lg-block" asp-action="Index" asp-controller="User"><i class="fa-solid fa-circle-user fa-2x"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link bg-light d-lg-none d-xl-none d-xxl-none" asp-action="Index" asp-controller="User">Профиль</a>
              </li>  
            </ul>            
          </div>
      </div>                                        
    </nav>
</div>

  <div class="mainCart mt-4">
          <div class="container">
            <h4 class="mainCart__title ">
                Корзина / @Model.Cart.Lines.Sum(s=>s.Quantity) товар
            </h4>
          <!-- /.mainCart__title -->
              <div class="mainCart__content border p-2 bg-light">
            @foreach(var c in Model.Cart.Lines)
            {
               <div class="mainCart__product row m-1 ">
                      <div class="col-md-3">
                          <img class="mainCart__img  rounded shadow" src="/img/Tovars/@{@c.tovar.NameImg}.jpg" alt="">
                      </div>
                      <div class="col-md-3">
                          <span class="fs-5">@c.tovar.name</span>
                      </div>
                      <div class="col-md-4  ">
                          <div class=" d-flex justify-content-center">
                            <form asp-action="RemoveItemFromCart" method="post">
                                <input type="hidden" name="TovarsId" value="@c.tovar.TovarsId">
                                <input type="hidden" name="returnUrl" value="@Model.ReturnUrl">
                                <button class=" h-100 btn btn-light  border">-</button>
                            </form>   
                            
                            <button class=" btn btn-light w-25 border">@c.Quantity</button>
                            <form asp-action="AddToCart" method="post">
                                <input type="hidden" name="TovarsId" value="@c.tovar.TovarsId">
                                <input type="hidden" name="returnUrl" value="@Model.ReturnUrl">
                                <button type="submit" class=" h-100 btn btn-light border">+</button>
                              </form>
                          </div>
                            
                            <form asp-action="RemoveFromCart" method="post">
                                <input type="hidden" name="TovarsId" value="@c.tovar.TovarsId">
                                <input type="hidden" name="returnUrl" value="@Model.ReturnUrl">
                                <button class=" btn btn-light w-100 mt-2 d-grid border" type="submit">Удалить товар</button>
                            </form>
                            
                      </div>
                      <div class="col-md-2 text-end ">
                          <span class="mainCart__Price">@Model.Cart.Lines.Where(s=>s.tovar.TovarsId==c.tovar.TovarsId).Sum(s=>s.tovar.price * c.Quantity).ToString("c")</span>
                      </div>
                  </div>
                  <!-- /.mainCart__product --> 
            }
            
              </div>
              <!-- /.content -->
             
          </div>
          <!-- /.container -->
      </div>
      <!-- /.mainCart -->

      <div class="btnCart mt-3">
          <div class="container">
              <div class="block row h-25 justify-content-end">
                    <span class="col-2 " >Итог: @Model.Cart.ComputeTotalVaule().ToString() ₽</span>
                    <a asp-action="Checkout" asp-controller="Order" class="col-lg-2 btn btn-primary" >Оформить заказ</a>
              </div>
          </div>
          <!-- /.container -->
      </div>
      <!-- /.btnCart -->
      <style>
          .mainCart__img {
    height: 215px;
    max-width: 196px;
}
      </style>