DiplomStore/Components/CartSummaryViewComponent.cs
using DiplomStore.BLL.DTO.Cart;
using Microsoft.AspNetCore.Mvc;

namespace DiplomStore.Components
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private CartDTO Cart;
        public CartSummaryViewComponent(CartDTO cart)
        {
            Cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(Cart);
        }
    }
}

DiplomStore/Controllers/CartController.cs
using DiplomStore.BLL.DTO;
using DiplomStore.BLL.Services.Intefaces;
using DiplomStore.ViewsModels.Cart;
using Microsoft.AspNetCore.Mvc;
using DiplomStore.BLL.DTO.Cart;
using DiplomStore.Domain.Entity;

namespace DiplomStore.Controllers
{
    public class CartController:Controller
    {
        private readonly ITovarService tovars;
        private readonly ITitleService Titles;
        private readonly ICategoryService Category;
        private readonly CartDTO cart;

        public CartController(ITovarService tv, ITitleService tit, ICategoryService cat, CartDTO car)
        {
            tovars = tv;
            Titles = tit;
            Category = cat;
            cart = car;
        }

        public IActionResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public IActionResult AddToCart(int TovarsId, string returnUrl)
        {
            Tovars tovar = tovars.GetTovar().FirstOrDefault(t=>t.TovarsId == TovarsId);
            if(tovar !=null)
            {
                cart.AddItem(tovar, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public IActionResult RemoveFromCart(int TovarsId, string returnUrl)
        {
            Tovars tovar = tovars.Models().FirstOrDefault(t => t.TovarsId == TovarsId);
            if (tovar != null)
            {
                cart.RemoveLine(tovar);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public IActionResult RemoveItemFromCart(int TovarsId, string returnUrl)
        {
            Tovars tovar = tovars.Models().FirstOrDefault(t => t.TovarsId == TovarsId);
            if (tovar != null)
            {                
                cart.RemoveItem(tovar);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

    }
}

DiplomStore/Controllers/TovarController.cs
using AutoMapper;
using DiplomStore.BLL.Services.Intefaces;
using DiplomStore.Domain.Entity;
using DiplomStore.ViewsModels.Category;
using DiplomStore.ViewsModels.Title;
using DiplomStore.ViewsModels.Tovar;
using Microsoft.AspNetCore.Mvc;

namespace DiplomStore.Controllers
{
    public class TovarController:Controller
    {
        private readonly ITovarService Tovars;
        private readonly ICategoryService Categories;
        private readonly ITitleService Titles;
        public TovarController(ITovarService ctx, ICategoryService categories, ITitleService titles)
        {
            Tovars = ctx;
            Categories = categories;
            Titles = titles;
        }
    /// <summary>
    /// Выводит товары связанные с категориями
    /// </summary>
    /// <param name="searhString">Поисковая строка</param>
    /// <param name="CategoriesId"></param>
    /// <param name="selectedTitle">Выбранный тайтл</param>
    /// <param name="page"></param>
    /// <returns></returns>
        [HttpGet]
        public IActionResult TovarAndCategoryList(string searhString, int CategoriesId, int[] selectedTitle, int page = 1)
        {
            TovarAndCategoryListViewModel TovarCategory = new TovarAndCategoryListViewModel();
            
            var map = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов Tovars в TovarViewModel                                    
            var tovars = map.Map<IEnumerable<Tovars>, List<TovarViewModel>>(Tovars.Models());
            //Находим товары связанные с категориями
            TovarCategory.Tovar = tovars.Where(p => p.category.CategoriesId == CategoriesId).ToList();
            //Всего товаров на странице
            int pageSize = 6;
            //Всего товаров
            var count = tovars.Count();
            //Получение товаров
            var item = tovars.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel(item, pageViewModel);
            TovarCategory.IndexViewModel = viewModel;
            
            var cat = Categories.Models().FirstOrDefault(p => p.CategoriesId == CategoriesId);
            var mapCategor = new MapperConfiguration(c => c.CreateMap<Categories, CategoryViewModel>()).CreateMapper();
            //сопоставление объектов Categories в CategoryViewModel                                    
            var categor = mapCategor.Map<Categories, CategoryViewModel>(cat);

            var mapTile = new MapperConfiguration(c => c.CreateMap<Titles, TitleViewModel>()).CreateMapper();
            //сопоставление объектов Titles в TitleViewModel          
            TovarCategory.Titles = mapTile.Map<IEnumerable<Titles>, List<TitleViewModel>>(Titles.Models().Where(p => p.tovars.Any(d => d.isValids) && p.tovars.Any(d => d.CategoryId == CategoriesId)));

            TovarCategory.Category = categor;
            List<TovarViewModel> t = new List<TovarViewModel>();
            if (!string.IsNullOrEmpty(searhString))
            {
                if(selectedTitle != null)
                {
                    foreach (var c in Titles.Models().Where(p => selectedTitle.Contains(p.TitlesId)))
                    {
                        // Добавляем в лист товары, связанных одной категорией или тайтлом
                        t.AddRange(item.Where(p => p.category.CategoriesId == CategoriesId & p.TitleId == c.TitlesId).ToList());

                    }
                    if (t.Count > 0)
                    {
                        //получаем товар по поисковой строке
                        TovarCategory.Tovar = t.Where(p=>p.name.ToLower().Contains(searhString.ToLower())).ToList();
                        TovarCategory.selectTitle.AddRange(selectedTitle);
                        return View("TovarAndCategoryList", TovarCategory);
                    }
                    else
                    {

                        t.AddRange(tovars.Where(p => p.name.ToLower().Contains(searhString.ToLower()) & p.category.CategoriesId == CategoriesId));
                        TovarCategory.Tovar = t;
                    }
                }

                
               
            }
            TovarCategory.Tovar = item;
            return View("TovarAndCategoryList",TovarCategory);
        }
        /// <summary>
        /// Выводит товары связанные с тайтлами
        /// </summary>
        /// <param name="TitleId">Поисковая строка</param>
        /// <param name="searhString"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult TovarAndTitleList(int TitleId , string searhString, int page=1)
        {
            TovarAndTitleViewModel TovarTitle = new TovarAndTitleViewModel();
            var map = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов TovarDTO в TovarListViewModel                                    
            var tovars = map.Map<IEnumerable<Tovars>, List<TovarViewModel>>(Tovars.Models());

            var tit = Titles.Models().FirstOrDefault(p => p.TitlesId == TitleId);
            var mapTile = new MapperConfiguration(c => c.CreateMap<Titles, TitleViewModel>()).CreateMapper();

            if (!string.IsNullOrEmpty(searhString))
            {   
                //Получаем товары по поисковой строке
                TovarTitle.tovars = tovars.Where(p => p.titles.TitlesId == TitleId & p.name.Contains(searhString)).ToList();
                //сопоставление объектов Titles в TitleViewModel                      
                TovarTitle.title = mapTile.Map<Titles, TitleViewModel>(tit);
                return View(TovarTitle);
            }
            int pageSize = 6;
            var count = tovars.Count();
            var item = tovars.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel(item, pageViewModel);
            TovarTitle.IndexViewModel = viewModel;

            TovarTitle.tovars = item.Where(p => p.titles.TitlesId == TitleId).ToList();
            ///сопоставление объектов Titles в TitleViewModel                      
            TovarTitle.title = mapTile.Map<Titles, TitleViewModel>(tit);
            return View(TovarTitle);
        }

        public IActionResult TovarIndex(int TovarId)
        {
            TovarsTitleViewModel TovarTitle = new TovarsTitleViewModel();
            var map = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов Tovars в TovarViewModel                                    
            var tovar = map.Map<Tovars, TovarViewModel>(Tovars.Models().FirstOrDefault(p=>p.TovarsId == TovarId ));
            TovarTitle.Tovar = tovar;
            var c = Titles.Models().FirstOrDefault(t=>t.TitlesId == tovar.TitleId);

            var maptitle = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов Tovars в TovarViewModel                                    
            var tovars = maptitle.Map<IEnumerable<Tovars>, List<TovarViewModel>>(Tovars.Models().Where(t => t.TitleId == tovar.TitleId && t.TovarsId !=TovarId));

            TovarTitle.Tovars = tovars;
            return View(TovarTitle);

        }
        /// <summary>
        /// Выводит товары свзяанные с категорией и выбраннысм тайтлами
        /// </summary>
        /// <param name="selectedTitle"></param>
        /// <param name="CategoriesId"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult IndexTovarOfTitle(int[] selectedTitle,int CategoriesId, int page = 1)
        {
            
            TovarAndCategoryListViewModel TovarCategory = new TovarAndCategoryListViewModel();
            var map = new MapperConfiguration(c => c.CreateMap<Tovars, TovarViewModel>()).CreateMapper();
            //сопоставление объектов TovarDTO в TovarListViewModel                                    
            var tovars = map.Map<IEnumerable<Tovars>, List<TovarViewModel>>(Tovars.Models());

            int pageSize = 6;
            var count = tovars.Count();
            var item = tovars.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel(item, pageViewModel);
            TovarCategory.IndexViewModel = viewModel;

            List<TovarViewModel> t = new List<TovarViewModel>();
            if(selectedTitle != null)
            {
                foreach (var c in Titles.Models().Where(p => selectedTitle.Contains(p.TitlesId)))
                {
                    t.AddRange(item.Where(p => p.category.CategoriesId == CategoriesId & p.TitleId == c.TitlesId).ToList());

                }
                if(t.Count >0)
                {
                    TovarCategory.Tovar = t;
                    TovarCategory.selectTitle.AddRange(selectedTitle);
                }
                else
                {
                    t.AddRange(tovars.Where(p => p.category.CategoriesId == CategoriesId));
                    TovarCategory.Tovar = t;
                }
                
            }
          
            var mapTile = new MapperConfiguration(c => c.CreateMap<Titles, TitleViewModel>()).CreateMapper();
            //сопоставление объектов TovarDTO в TovarListViewModel                                    
            var Title = mapTile.Map<IEnumerable<Titles>, List<TitleViewModel>>(Titles.Models().Where(p => p.tovars.Any(d => d.isValids) && p.tovars.Any(d => d.CategoryId == CategoriesId)));
           

DiplomStore/Controllers/UserController.cs
using AutoMapper;
using DiplomStore.BLL.Services.Intefaces;
using DiplomStore.Domain.Entity;
using DiplomStore.ViewsModels.Order;
using DiplomStore.ViewsModels.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace DiplomStore.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IOrderService db;
        private readonly UserManager<AppUser> userManager;
        public UserController(IOrderService orderService, UserManager<AppUser> _userManager)
        {
            db = orderService;
            userManager = _userManager;
        }
        public ViewResult Index()
        {
            UserViewModel userOrd = new UserViewModel();
            var user = userManager.Users.FirstOrDefault(p => p.UserName == User.Identity.Name);
            var map = new MapperConfiguration(c => c.CreateMap<Order, OrderViewModel>()).CreateMapper();
            //сопоставление объектов Order в OrderViewModel                    
            var order = map.Map<IEnumerable<Order>, List<OrderViewModel>>(db.Orders().Where(p => p.User.Id == user.Id));
            userOrd.orders = order;

            return View(userOrd);
        }
        public IActionResult DeleteOrder(int IdOrder)
        {
            if (IdOrder != 0)
            {
                db.Delete(IdOrder);
                return RedirectToAction("Index");
            }
            return View("Index");
        }
    }
}

DiplomStore/Views/Tovar/TovarAndCategoryList.cshtml
@model TovarAndCategoryListViewModel
@{Layout="_Layout";}
<div class="navn  sticky-top ">
    <nav class="navbar navbar-expand-lg navbar-light shadow-lg "style="background-color: #1968AA">
      <div class="container ">
        <a asp-action="Index" asp-controller="Home" class="navbar-brand d-none d-lg-flex" >
          <img src="~/img/logo/logo-1.jpg" class="" alt="Logo" />
       
        </a>
        <form class="d-flex w-75 " asp-action="TovarSearch" asp-controller="Tovar"  method="get">          
          <input class="form-control me-2" name="searhString" type="search" placeholder="Поиск" aria-label="Search">          
        </form>
        <div class="container-fluid  w-25">        
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
         
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 w-100">
              <li class="nav-item text-center rounded-1 w-100 bg-light " >
                  @await Component.InvokeAsync("CartSummary")
              </li>
              <li class="rounded-1 bg-light w-100 d-lg-none d-xl-none d-xxl-none nav-item ">
                <a class="nav-link" asp-action="TitleIndex" asp-controller="Home">Список тайтолов</a>
              </li> 
               <li class="rounded-1 bg-light w-100 d-lg-none d-xl-none d-xxl-none nav-item ">
                <a class="nav-link" asp-action="CategoryIndex" asp-controller="Home">Список категорий</a>
              </li>
              <li class="nav-item ms-3">
                <a class="nav-link text-light  d-none d-xxl-block d-xl-block d-lg-block" asp-action="Index" asp-controller="User"><i class="fa-solid fa-circle-user fa-2x"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link bg-light d-lg-none d-xl-none d-xxl-none" asp-action="Index" asp-controller="User">Профиль</a>
              </li>  
            </ul>            
          </div>
      </div>                                        
    </nav>
</div>

<div class="main mt-3">
        <div class="container">
          <div class="main__Title mb-4">
            @Model.Category.name / @Model.Tovar.Count() товаров
          </div>
          <!-- /.main__Title -->
          <div class="row">
            <div class="col-lg-3 d-none d-xxl-block d-xl-block d-lg-block">
              <div class="main__search">
                <form asp-action="TovarAndCategoryList" method="get" class="d-flex">
                  <input class="form-control " name="searhString" type="search" placeholder="Поиск товара" aria-label="Search">          
                   <input type="hidden" name="CategoriesId" value="@Model.Category.CategoriesId" />
                        @foreach(var c in Model.Titles)
                         {                             
                             <input name="selectedTitle" value="@(Model.selectTitle.Contains(@c.TitlesId) ? @c.TitlesId : " ")" type="hidden"/><br/>
                         }
                        
                </form>
              </div>
             
              <!-- /.main__search -->
              <div class="main__categor mt-3 border  p-3">
                <div class="main__subTitle mb-3">Тайтл</div>
                <!-- /.main__subTitle -->                                 
                      
                    <form asp-action="IndexTovarOfTitle" asp-controller="Tovar" method="get" class="main__searhcCategor ">
                    <div class="mt-2 main__filterItems">
                                                    
                     <div class="contain">
                       
                         @foreach(var c in Model.Titles)
                         {                             
                             <input name="selectedTitle" value="@c.TitlesId" type="checkbox"
                             @(Model.selectTitle.Contains(@c.TitlesId) ? "checked" : " ")/>@c.name<br/>
                         }                                                
                    </div>
                      
                    </div>
                    <input type="hidden" name="CategoriesId" value="@Model.Category.CategoriesId" />
                    <!-- /.main__filterItems -->
                    <div class="main__buttons d-grid gap-2 mt-3" >
                      <button class="btn main__secbut shadow btn-primary" type="submit">Принять</button>

                    <a asp-route-selectedTitle="0" 
                    asp-route-CategoriesId="@Model.Category.CategoriesId" 
                    asp-action="IndexTovarOfTitle" class="btn border main__secbut shadow">Сбросить</a>      
                    </div>
                    <!-- /.main__buttons -->
                </form>
                <!-- /.main__searhcCategor -->
                
              </div>
              <!-- /.main__categor -->
             
            </div>
            <div class="col-lg-9 row">
                @if(Model.Tovar == null || Model.Tovar.Count <= 0)
                {
                    <p>Упс, ничего не найдено</p>
                }
                else
                {
                   @foreach(var c in Model.Tovar)
                {
                     <div class="col-lg-4 col-md-5 col-sm-5 col-5 mb-3">
                 <div class="tovars__tit shadow-lg rounded-3 border border-1 text-center">
                  <a asp-action="TovarIndex" asp-route-TovarId="@c.TovarsId" class="tovars__links link-dark">
                    <img src="/img/Tovars/@{@c.NameImg}.jpg" alt="" class="tovars__img rounded">
                    <div class="tovars__span">@c.name</div>
                  </a>                
                    <!-- /.tovars__span -->
                    <div class="tovars__info d-flex p-2 justify-content-between mt-3">
                      <div class="tovars__price">@c.price.ToString() ₽</div>
                        <!-- /.towars__price -->
                      <a asp-action="TovarIndex" asp-route-TovarId="@c.TovarsId"  class="tovars__links border border-1 rounded-3">
                        <div class="tovars__cart"> <i class="fa-solid fa-cart-shopping"></i></div>                  
                      </a>                               
                     </div>              
                    </div>                      
                    </div>
                } 
                }
                <page-link page-categories-id="@Model.Category.CategoriesId" page-model="@Model.IndexViewModel.PageViewModel" page-action="TovarAndCategoryList"></page-link>
               
              
            </div>
          </div>
        </div>
      </div>
    

      

DiplomStore/Views/Tovar/TovarIndex.cshtml
@model TovarsTitleViewModel
@{Layout="_Layout";}

<div class="navn  sticky-top ">
    <nav class="navbar navbar-expand-lg navbar-light shadow-lg "style="background-color: #1968AA">
      <div class="container ">
        <a asp-action="Index" asp-controller="Home" class="navbar-brand d-none d-lg-flex" >
          <img src="~/img/logo/logo-1.jpg" class="" alt="Logo" />
       
        </a>
        <form class="d-flex w-75 " asp-action="TovarSearch" asp-controller="Tovar"  method="get">          
          <input class="form-control me-2" name="searhString" type="search" placeholder="Поиск" aria-label="Search">          
        </form>
        <div class="container-fluid  w-25">        
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
         
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 w-100">
              <li class="nav-item text-center rounded-1 w-100 bg-light " >
                  @await Component.InvokeAsync("CartSummary")
              </li>
              <li class="rounded-1 bg-light w-100 d-lg-none d-xl-none d-xxl-none nav-item ">
                <a class="nav-link" asp-action="TitleIndex" asp-controller="Home">Список тайтолов</a>
              </li> 
               <li class="rounded-1 bg-light w-100 d-lg-none d-xl-none d-xxl-none nav-item ">
                <a class="nav-link" asp-action="CategoryIndex" asp-controller="Home">Список категорий</a>
              </li>
              <li class="nav-item ms-3">
                <a class="nav-link text-light  d-none d-xxl-block d-xl-block d-lg-block" asp-action="Index" asp-controller="User"><i class="fa-solid fa-circle-user fa-2x"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link bg-light d-lg-none d-xl-none d-xxl-none" asp-action="Index" asp-controller="User">Профиль</a>
              </li>  
            </ul>            
          </div>
      </div>                                        
    </nav>
</div>

<div class="mainTovar mt-4">
           <div class="container border bg-light">
               <h3 class="mainTovar__title">@Model.Tovar.name</h3>
               <!-- /.main__title -->
               <div class="mainTovar__tovarifo row">

                <div class="mainTovar__tovar  p-3 col-lg-3 d-block">
                    <div class="mb-3">                        
                        <img src="/img/Tovars/@{@Model.Tovar.NameImg}.jpg" alt="" class="mainTovar__img shadow-lg rounded">                                         
                    </div>                    
                </div>
                <!-- /.main__tovar -->
                <div class="mainTovar__info col-lg-5 ms-lg-5 p-3">
                  <div class="mainTovar__charactirictic">
                    <h5 class="mainTovar__subTitle">
                      Характеристика товара
                    </h5>
                    <!-- /.main__subTitle -->
                    <div class="main__name">
                      <span>Тайтл:</span>
                      <span>@Model.Tovar.titles.name</span>
                    </div>
                    <!-- /.main__name -->
                    @if (Model.Tovar.category.name.Contains("Фигурк"))
                    {
                       <div class="main__material">
                       
                      <span>Материал:</span>
                      <span>@Model.Tovar.materials</span>
                    </div>
                    <!-- /.main__material -->
                    <div class="main__hight">
                      <span>Высота:</span>
                      <span>@Model.Tovar.hight</span>
                        </div>
                    }
                    else if (Model.Tovar.category.name.Contains("Рюкзак"))
                    {
                        <div class="main__material">
                        
                      <span>Материал:</span>
                      <span>@Model.Tovar.materials</span>
                    </div>
                    <!-- /.main__material -->
                    <div class="main__hight">
                      <span>Размеры:</span>
                      <span>@Model.Tovar.hight x @Model.Tovar.hight x @Model.Tovar.width</span>
                        </div>

                    }
                    else if (Model.Tovar.category.name.Contains("Шоппер"))
                    {
                        <div class="main__material">
                      
                      <span>Материал:</span>
                      <span>@Model.Tovar.materials</span>
                    </div>
                    <!-- /.main__material -->
                    <div class="main__hight">
                      <span>Размеры:</span>
                      <span>@Model.Tovar.hight"x"@Model.Tovar.hight</span>
                        </div>
                    }
                    else if (Model.Tovar.category.name.Contains("Значок деревянный"))
                    {
                        <div class="main__material">
                      
                      <span>Материал:</span>
                      <span>@Model.Tovar.materials</span>
                    </div>
                    <!-- /.main__material -->
                    <div class="main__hight">
                      <span>Размеры:</span>
                      <span>@Model.Tovar.hight"x"@Model.Tovar.hight</span>
                        </div>
                    }
                    
                    else if (Model.Tovar.category.name.Contains("Кружк"))
                    {
                        <div class="main__material">
        
                      <span>Формат:</span>
                      <span>@Model.Tovar.materials</span>
                    </div>
                    <!-- /.main__material -->
                    <div class="main__hight">
                      <span>Объём:</span>
                      <span>@Model.Tovar.hight</span>
                        </div>
                    }
                     else if (Model.Tovar.category.name.Contains("Манг"))
                    {
                        <div class="main__material">
      
                      <span>Бренд:</span>
                      <span>@Model.Tovar.materials</span>
                    </div>
                    <!-- /.main__material -->
                    <div class="main__hight">
                      <span>Размеры:</span>
                      <span>@Model.Tovar.hight"x"@Model.Tovar.hight</span>
                        </div>
                        <div class="main__hight">
                      <span>Год выпуска:</span>
                      <span></span>
                        </div>
                        <div class="main__hight">
                      <span>Автор:</span>
                      <span></span>
                        </div>
                         <div class="main__hight">
                      <span>Количество страниц:</span>
                      <span></span>
                        </div>
                    }
                  </div>
                  <!-- /.main__charactirictic -->
                </div>                
                <!-- /.main__info -->
                <div class="col-lg-3 p-2">
                  <div class="mainTovar__btns">
                    <h5 class="mainTovar__price">@Model.Tovar.price.ToString() ₽</h5>
                    <form asp-action="AddToCart" asp-controller="Cart" method="post">
                        <input type="hidden" name="TovarsId" value="@Model.Tovar.TovarsId" />
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button type="submit" class="mainTovar__btn btn btn-primary d-grid">Купить</button>     
                    </form>
                                   
                  </div>                  
                </div>
               </div>
               <!-- /.main__tovarifo -->               
           </div>
           <!-- /.container -->
       </div>
       <!-- /.main -->

       <div class="Tovars">
          <div class="container">
            <div class="row mt-5">
                <span class="fs-5 mb-3">Товары по тайтлу @Model.Tovar.titles.name</span>
                @foreach(var c in Model.Tovars)
            {
                <div class="col-xl-3  col-6 mb-2 ">
                <div class="tovars__tit shadow-lg rounded-3 border border-1 text-center">
                  <a asp-action="TovarIndex" asp-route-TovarId="@c.TovarsId" class="tovars__links link-dark">
                    <img src="/img/Tovars/@{@c.NameImg}.jpg" alt="" class="tovars__img rounded">
                    <div class="tovars__span">@c.name</div>
                  </a>                
                    <!-- /.tovars__span -->
                    <div class="tovars__info d-flex p-2 justify-content-between mt-3">
                      <div class="tovars__price">@c.price.ToString() ₽</div>
                        <!-- /.towars__price -->
                      <a asp-action="TovarIndex" asp-route-TovarId="@c.TovarsId" class="tovars__links border border-1 rounded-3">
                        <div class="tovars__cart"> <i class="fa-solid fa-cart-shopping"></i></div>                  
                      </a>                               
                     </div>              
                </div>                      
              </div>
            }
            

            </div>
            
          </div>
       </div>
       <!-- /.main__tovars -->
       <style>
           .mainTovar__img {
    height: 380px;
    max-width: 100%;
}
       </style>